CREATE TABLE users (
user_id INT(6) AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR (15) NOT NULL,
last_name VARCHAR (20) NOT NULL,
username VARCHAR (25) NOT NULL,
email VARCHAR (25) NOT NULL,
password VARCHAR (50) NOT NULL
)
*